#version: '3.8'


services:
  bott:
    image: bott:latest
    container_name: bott
    privileged: true
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./:/opt/bott
    working_dir: /opt/bott
    command: /bin/bash -c "npm install -D && npm run dev"
    restart: always