version: '3.8'

services:
  node-app:
    image: node:14-buster
    container_name: telegram-node-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    restart: always
    command: ["npm", "start"]